install_data(
  'com.niksnakshosting.NiksnaksHosting.desktop',
  install_dir: get_option('datadir') / 'applications'
)

install_data(
  'com.niksnakshosting.NiksnaksHosting.metainfo.xml',
  install_dir: get_option('datadir') / 'metainfo'
)

install_data(
  'com.niksnakshosting.NiksnaksHosting.svg',
  install_dir: get_option('datadir') / 'icons/hicolor/scalable/apps'
)

install_data(
  'com.niksnakshosting.NiksnaksHosting-symbolic.svg',
  install_dir: get_option('datadir') / 'icons/hicolor/symbolic/apps'
)

install_data(
  'com.niksnakshosting.Crucible.svg',
  install_dir: get_option('datadir') / 'icons/hicolor/scalable/apps'
)

install_data(
  'com.niksnakshosting.Carabiner.svg',
  install_dir: get_option('datadir') / 'icons/hicolor/scalable/apps'
)

install_data(
  'sliders-horizontal-symbolic.svg',
  install_dir: get_option('datadir') / 'icons/hicolor/scalable/actions'
)
